export const seedEvents = [
  {
    eventName: 'WTW/Willis',
    businessUnit: 'Kenyon',
    eventType: 'Conference',
    region: 'EMEA',
    city: 'Istanbul',
    country: 'Turkey',
    venue: 'Rixos Tersane Istanbul',
    startDate: "2026-05-12",
    endDate: "2026-05-14",
    numberOfDays: 3,
    salesStaffAttending: 2,
    staffNames: null,
    eventBoothCost: 10000,
    estDailyRate: 400,
    totalDailyRate: 2400,
    flightCostPerPerson: 1500,
    totalFlightCost: 3000,
    totalTravelCost: 5400,
    totalEventCost: 15400,
    budgetMonth: 'Apr',
    status: 'Confirmed',
    sponsorshipLevel: 'Silver',
    boothNumber: null,
    eventWebsiteUrl: 'https://www.wtwco.com/en-se/insights/campaigns/global-aviation-and-space-events',
    eventDescription: 'The Willis Aviation Conference brings together the aviation and insurance industries to explore how the sector can manage the growing complexity of risk, both now and in the future. From safety priorities to operational challenges and data use, the conference examines key factors shaping a more resilient and sustainable future for aviation. Hosted at Rixos Tersane Istanbul.',
    targetAudience: 'Airline risk managers, aviation insurance underwriters, insurance brokers, reinsurers, airline finance executives, and aviation liability professionals',
    keyTopics: 'Aviation insurance market trends, risk management complexity, safety priorities, operational challenges, data use in aviation, resilience and sustainability',
    productsToFeature: null,
    preEventGoals: 'Silver sponsor. Sponsor deadlines: 13 Feb - company bio and logo; 27 Feb - sponsor video; 13 Mar - booth artwork; 7 Apr - ship promotional items. Booth: Silver (240x250cm backdrop, desk 120x100x50). Contact: Kate Churchyard (registrations), Lauren Dalton (sponsor video), Daniel Brzezinski (hotel deliveries).',
    postEventNotes: null,
    wordpressArticleStatus: 'Not Started',
    articleUrl: null,
  },
  {
    eventName: 'Aerofriedrichschafen',
    businessUnit: 'TrustFlight',
    eventType: 'Trade Show',
    region: 'EMEA',
    city: 'Friedrichshafen',
    country: 'Germany',
    venue: 'Messe Friedrichshafen',
    startDate: "2026-04-22",
    endDate: "2026-04-25",
    numberOfDays: 4,
    salesStaffAttending: 2,
    staffNames: null,
    eventBoothCost: 4200,
    estDailyRate: 401,
    totalDailyRate: 3208,
    flightCostPerPerson: 1500,
    totalFlightCost: 3000,
    totalTravelCost: 6208,
    totalEventCost: 10408,
    budgetMonth: 'Apr',
    status: 'Planned',
    sponsorshipLevel: null,
    boothNumber: null,
    eventWebsiteUrl: 'https://www.aero-expo.com/',
    eventDescription: 'AERO Friedrichshafen is the global trade show for general aviation, showcasing over 320 aircraft across 12 exhibition halls. With 756+ exhibitors from 38+ countries and 32,000+ attendees, it is the international general aviation community\'s annual meeting place.',
    targetAudience: 'General aviation pilots, aircraft manufacturers, avionics suppliers, flight schools, business aviation operators, and aviation enthusiasts',
    keyTopics: 'Electric flight (e-flight), advanced avionics, new propulsion systems, business aviation, drones/UAVs, ultralight aircraft, helicopters, sustainable aviation',
    productsToFeature: null,
    preEventGoals: null,
    postEventNotes: null,
    wordpressArticleStatus: 'Not Started',
    articleUrl: null,
  },
  {
    eventName: 'ISJ Leaders in Security Conference Middle East',
    businessUnit: 'Redline',
    eventType: 'Conference',
    region: 'EMEA',
    city: 'Dubai',
    country: 'United Arab Emirates',
    venue: 'Grosvenor House Hotel, Dubai Marina',
    startDate: "2026-05-06",
    endDate: "2026-05-06",
    numberOfDays: 1,
    salesStaffAttending: 1,
    staffNames: null,
    eventBoothCost: 2000,
    estDailyRate: 400,
    totalDailyRate: 400,
    flightCostPerPerson: 1000,
    totalFlightCost: 1000,
    totalTravelCost: 1400,
    totalEventCost: 3400,
    budgetMonth: 'May',
    status: 'Planned',
    sponsorshipLevel: null,
    boothNumber: null,
    eventWebsiteUrl: 'https://isjleadersinsecurity.com/',
    eventDescription: 'The ISJ Leaders in Security Conference is the premier event for senior professionals working in the Middle East and Africa security industry. The conference brings together 120+ senior professionals and 30+ expert speakers representing major commercial entities, transport authorities, regulatory bodies, and infrastructure departments.',
    targetAudience: 'Senior security professionals, corporate security directors, government security officials, transport authority security managers, regulatory bodies, and infrastructure security operators across the Middle East and Africa',
    keyTopics: 'Cybersecurity, supply chain security, physical security innovation, regional threat landscape, security strategy, critical infrastructure protection, regulatory developments',
    productsToFeature: null,
    preEventGoals: null,
    postEventNotes: null,
    wordpressArticleStatus: 'Not Started',
    articleUrl: null,
  },
  {
    eventName: 'Safety Management International Collaboration Group',
    businessUnit: 'Baines Simmons',
    eventType: 'Conference',
    region: 'EMEA',
    city: 'Crawley',
    country: 'United Kingdom',
    venue: 'Crowne Plaza, Crawley',
    startDate: "2026-05-12",
    endDate: "2026-05-12",
    numberOfDays: 1,
    salesStaffAttending: 1,
    staffNames: null,
    eventBoothCost: 1500,
    estDailyRate: 400,
    totalDailyRate: 400,
    flightCostPerPerson: 1000,
    totalFlightCost: 1000,
    totalTravelCost: 1400,
    totalEventCost: 2900,
    budgetMonth: 'May',
    status: 'Attending',
    sponsorshipLevel: null,
    boothNumber: null,
    eventWebsiteUrl: 'https://consultations.caa.co.uk/safety-and-airspace-regulation-group/c97d1c97/',
    eventDescription: 'The SM ICG Industry Day is held alongside the biannual plenary meeting of the Safety Management International Collaboration Group, a cooperative effort among aviation regulators including the FAA, EASA, and Transport Canada. Themed \'Advancing SMS Performance to Serve a Growing, Innovative, Global Aviation Community\', the day provides a forum for aviation professionals to connect with regulators and discuss safety management.',
    targetAudience: 'Aerodrome and airport operators, airlines, air traffic control personnel, airworthiness and maintenance organisations, general aviation operators, ground handling providers, UAV operators, military representatives, industry bodies',
    keyTopics: 'SMS implementation and performance, safety oversight harmonisation, safety data sharing, regulatory collaboration, safety performance measurement, advancing safety management for a growing and innovative aviation community',
    productsToFeature: null,
    preEventGoals: null,
    postEventNotes: null,
    wordpressArticleStatus: 'Not Started',
    articleUrl: null,
  },
  {
    eventName: 'AGM AACO',
    businessUnit: 'Kenyon',
    eventType: 'Conference',
    region: 'EMEA',
    city: null,
    country: 'Saudi Arabia',
    venue: null,
    startDate: null,
    endDate: null,
    numberOfDays: 3,
    salesStaffAttending: 2,
    staffNames: null,
    eventBoothCost: 0,
    estDailyRate: 401,
    totalDailyRate: 2406,
    flightCostPerPerson: 1501,
    totalFlightCost: 3002,
    totalTravelCost: 5408,
    totalEventCost: 5408,
    budgetMonth: 'May',
    status: 'Planned',
    sponsorshipLevel: null,
    boothNumber: null,
    eventWebsiteUrl: 'https://www.aaco.org/events',
    eventDescription: 'The AACO Annual General Meeting brings together CEOs and senior executives of Arab air carriers, alongside industry stakeholders and partners, to develop strategies and a roadmap for AACO and the Arab aviation industry. The 58th AGM was in Rabat, Morocco; the 59th is expected in Saudi Arabia.',
    targetAudience: 'CEOs and senior leadership of AACO member airlines, partner airlines, aviation industry stakeholders, OEMs, MROs, and government aviation officials from the Arab world',
    keyTopics: 'Arab aviation industry strategy, fleet development, airline partnerships and alliances, sustainability, passenger experience, aviation regulation, regional connectivity',
    productsToFeature: null,
    preEventGoals: null,
    postEventNotes: null,
    wordpressArticleStatus: 'Not Started',
    articleUrl: null,
  },
  {
    eventName: 'IATA Ground Handling Conference',
    businessUnit: 'TrustFlight',
    eventType: 'Conference',
    region: 'EMEA',
    city: 'Cairo',
    country: 'Egypt',
    venue: 'InterContinental Citystars Cairo',
    startDate: "2026-05-19",
    endDate: "2026-05-21",
    numberOfDays: 3,
    salesStaffAttending: 2,
    staffNames: null,
    eventBoothCost: 7500,
    estDailyRate: 400,
    totalDailyRate: 2400,
    flightCostPerPerson: 1500,
    totalFlightCost: 3000,
    totalTravelCost: 5400,
    totalEventCost: 12900,
    budgetMonth: 'May',
    status: 'Planned',
    sponsorshipLevel: null,
    boothNumber: null,
    eventWebsiteUrl: 'https://www.iata.org/en/events/all/iata-ground-handling-conference/',
    eventDescription: 'The 38th IATA Ground Handling Conference (IGHC), hosted by EgyptAir, attracts over 800 delegates from airlines, ground service providers, airports, and manufacturers to promote standardisation, innovation, and sustainable development in ground operations.',
    targetAudience: 'Airlines, airports, ground service providers, ground handling equipment manufacturers, technology solution providers, and aviation operations professionals',
    keyTopics: 'Ground operations safety, digital transformation in ground handling, industry standardisation, sustainable ground operations, baggage handling innovation, ramp safety, turnaround efficiency',
    productsToFeature: null,
    preEventGoals: null,
    postEventNotes: null,
    wordpressArticleStatus: 'Not Started',
    articleUrl: null,
  },
  {
    eventName: 'ALTA Safety and Flights Ops Conference',
    businessUnit: 'Kenyon',
    eventType: 'Conference',
    region: 'LATAM',
    city: 'Mendoza',
    country: 'Argentina',
    venue: null,
    startDate: '2026-06-16',
    endDate: '2026-06-18',
    numberOfDays: 3,
    salesStaffAttending: 1,
    staffNames: null,
    eventBoothCost: 2500,
    estDailyRate: 400,
    totalDailyRate: 1200,
    flightCostPerPerson: 1500,
    totalFlightCost: 1500,
    totalTravelCost: 2700,
    totalEventCost: 5200,
    budgetMonth: 'Jun',
    status: 'Planned',
    sponsorshipLevel: null,
    boothNumber: null,
    eventWebsiteUrl: 'https://alta.aero/conferences/',
    eventDescription: 'The ALTA Aviation Safety, Flight Ops & Training Summit is the largest aviation safety and training summit in Latin America and the Caribbean. It rotates among major LATAM cities (Lima 2024, Mexico City 2025; 2026 location TBA).',
    targetAudience: 'Airline safety professionals, flight operations managers, training specialists, civil aviation authorities, manufacturers, airports, air traffic control organisations, and aviation schools across Latin America and the Caribbean',
    keyTopics: 'Aviation safety management, flight operations standards, pilot training, crew resource management, regulatory compliance in LATAM, safety culture, operational risk management',
    productsToFeature: null,
    preEventGoals: null,
    postEventNotes: null,
    wordpressArticleStatus: 'Not Started',
    articleUrl: null,
  },
  {
    eventName: 'Aircraft IT, EMEA',
    businessUnit: 'TrustFlight',
    eventType: 'Conference',
    region: 'EMEA',
    city: 'Noordwijk',
    country: 'Netherlands',
    venue: 'Hotel NH Noordwijk Conference Centre',
    startDate: "2026-06-09",
    endDate: "2026-06-10",
    numberOfDays: 3,
    salesStaffAttending: 2,
    staffNames: null,
    eventBoothCost: 10000,
    estDailyRate: 400,
    totalDailyRate: 2400,
    flightCostPerPerson: 1000,
    totalFlightCost: 2000,
    totalTravelCost: 4400,
    totalEventCost: 14400,
    budgetMonth: 'Jun',
    status: 'Planned',
    sponsorshipLevel: null,
    boothNumber: null,
    eventWebsiteUrl: 'https://aircraftcommerceevents.com/event/2026-airline-aerospace-mro-flight-operations-it-conference-emea/',
    eventDescription: 'The Airline & Aerospace MRO & Flight Operations IT Conference EMEA attracts 600+ attendees with 60+ leading MRO and flight operations IT vendors for case studies, keynotes, workshops and vendor showcases.',
    targetAudience: 'Airlines, MROs, OEMs, IT vendors, regulators, and consultants from across the EMEA region focused on MRO and flight operations technology',
    keyTopics: 'MRO IT systems, flight operations software, digital transformation, paperless operations, predictive analytics, regulatory compliance technology, sustainability solutions',
    productsToFeature: null,
    preEventGoals: null,
    postEventNotes: null,
    wordpressArticleStatus: 'Not Started',
    articleUrl: null,
  },
  {
    eventName: 'Regional Air Carriers Cargo Association',
    businessUnit: 'TrustFlight',
    eventType: 'Conference',
    region: 'NA',
    city: 'Scottsdale',
    country: 'United States',
    venue: 'Hilton Scottsdale Resort & Villas',
    startDate: "2026-10-27",
    endDate: "2026-10-29",
    numberOfDays: 3,
    salesStaffAttending: 1,
    staffNames: null,
    eventBoothCost: 4000,
    estDailyRate: 400,
    totalDailyRate: 1200,
    flightCostPerPerson: 500,
    totalFlightCost: 500,
    totalTravelCost: 1700,
    totalEventCost: 5700,
    budgetMonth: 'Jun',
    status: 'Planned',
    sponsorshipLevel: null,
    boothNumber: null,
    eventWebsiteUrl: 'https://www.raccaonline.org/annual-conference',
    eventDescription: 'The RACCA Annual Conference is the premier gathering for regional air cargo professionals, themed \'Stronger Together: Safety Through Shared Information and Insights\'. Attendees engage with experts, exchange critical safety data, and build collaborative relationships.',
    targetAudience: 'On-demand cargo aircraft operators, regional air cargo carriers, cargo airline executives, safety professionals, aviation suppliers',
    keyTopics: 'Aviation safety, safety data sharing, best practices for regional air cargo operations, regulatory compliance, operational efficiency, industry collaboration',
    productsToFeature: null,
    preEventGoals: null,
    postEventNotes: null,
    wordpressArticleStatus: 'Not Started',
    articleUrl: null,
  },
  {
    eventName: 'ALTA Safety and Flights Ops Conference',
    businessUnit: 'TrustFlight',
    eventType: 'Conference',
    region: 'LATAM',
    city: 'Mendoza',
    country: 'Argentina',
    venue: null,
    startDate: '2026-06-16',
    endDate: '2026-06-18',
    numberOfDays: 3,
    salesStaffAttending: 1,
    staffNames: null,
    eventBoothCost: 2500,
    estDailyRate: 400,
    totalDailyRate: 1200,
    flightCostPerPerson: 1500,
    totalFlightCost: 1500,
    totalTravelCost: 2700,
    totalEventCost: 5200,
    budgetMonth: 'Jun',
    status: 'Planned',
    sponsorshipLevel: null,
    boothNumber: null,
    eventWebsiteUrl: 'https://alta.aero/conferences/',
    eventDescription: 'The ALTA Aviation Safety, Flight Ops & Training Summit is the largest aviation safety and training summit in Latin America and the Caribbean. It rotates among major LATAM cities (Lima 2024, Mexico City 2025; 2026 location TBA).',
    targetAudience: 'Airline safety professionals, flight operations managers, training specialists, civil aviation authorities, manufacturers, airports, air traffic control organisations, and aviation schools across Latin America and the Caribbean',
    keyTopics: 'Aviation safety management, flight operations standards, pilot training, crew resource management, regulatory compliance in LATAM, safety culture, operational risk management',
    productsToFeature: null,
    preEventGoals: null,
    postEventNotes: null,
    wordpressArticleStatus: 'Not Started',
    articleUrl: null,
  },
  {
    eventName: 'Flight Safety Foundation Networking and Awards Dinner',
    businessUnit: 'Baines Simmons',
    eventType: 'Dinner/Reception',
    region: 'NA',
    city: 'Washington, D.C.',
    country: 'United States',
    venue: 'National Press Club, 529 14th St NW',
    startDate: "2026-07-07",
    endDate: "2026-07-07",
    numberOfDays: 1,
    salesStaffAttending: 2,
    staffNames: null,
    eventBoothCost: 2000,
    estDailyRate: 400,
    totalDailyRate: 800,
    flightCostPerPerson: 1500,
    totalFlightCost: 3000,
    totalTravelCost: 3800,
    totalEventCost: 5800,
    budgetMonth: 'Jul',
    status: 'Planned',
    sponsorshipLevel: null,
    boothNumber: null,
    eventWebsiteUrl: 'https://flightsafety.org/networking-dinner/',
    eventDescription: 'The Flight Safety Foundation Annual Networking and Awards Dinner draws approximately 200 aviation professionals including safety experts, regulators, and industry executives. Features the presentation of the Gloria Heath Trophy and the Richard Crane Award.',
    targetAudience: 'Aviation safety professionals, airline executives, regulatory officials, aviation industry leaders, Flight Safety Foundation members and supporters',
    keyTopics: 'Aviation safety leadership recognition, industry networking, women\'s achievements in civil aviation, corporate safety leadership, advancing aviation safety collaboration',
    productsToFeature: null,
    preEventGoals: null,
    postEventNotes: null,
    wordpressArticleStatus: 'Not Started',
    articleUrl: null,
  },
  {
    eventName: 'CBAA 2026',
    businessUnit: 'TrustFlight',
    eventType: 'Conference',
    region: 'NA',
    city: 'Calgary',
    country: 'Canada',
    venue: 'TBD',
    startDate: "2026-06-09",
    endDate: "2026-06-11",
    numberOfDays: 3,
    salesStaffAttending: 1,
    staffNames: null,
    eventBoothCost: 1000,
    estDailyRate: 400,
    totalDailyRate: 1200,
    flightCostPerPerson: 0,
    totalFlightCost: 0,
    totalTravelCost: 1200,
    totalEventCost: 2200,
    budgetMonth: 'Jul',
    status: 'Planned',
    sponsorshipLevel: null,
    boothNumber: null,
    eventWebsiteUrl: 'https://www.cbaa-acaa.ca/cbaa_2026_convention.php',
    eventDescription: 'The CBAA Annual Convention is Canada\'s premier business aviation event, bringing together over 700 business aviation leaders for networking, collaboration, and knowledge-sharing in the Canadian business aviation community.',
    targetAudience: 'Business aviation operators, corporate flight departments, FBOs, aircraft manufacturers, service providers, and decision-makers in Canadian business aviation',
    keyTopics: 'Canadian business aviation policy, safety, operational excellence, sustainability, workforce development, regulatory updates, technology innovation',
    productsToFeature: null,
    preEventGoals: null,
    postEventNotes: null,
    wordpressArticleStatus: 'Not Started',
    articleUrl: null,
  },
  {
    eventName: 'International Security Expo',
    businessUnit: 'Redline',
    eventType: 'Trade Show',
    region: 'EMEA',
    city: 'London',
    country: 'United Kingdom',
    venue: 'Olympia London',
    startDate: "2026-09-29",
    endDate: "2026-09-30",
    numberOfDays: 3,
    salesStaffAttending: 2,
    staffNames: null,
    eventBoothCost: 7000,
    estDailyRate: 400,
    totalDailyRate: 2400,
    flightCostPerPerson: 0,
    totalFlightCost: 0,
    totalTravelCost: 2400,
    totalEventCost: 9400,
    budgetMonth: 'Sep',
    status: 'Planned',
    sponsorshipLevel: null,
    boothNumber: null,
    eventWebsiteUrl: 'https://www.internationalsecurityexpo.com',
    eventDescription: 'International Security Expo is the UK government-endorsed flagship security event, bringing together over 10,000 professionals responsible for the security and resilience of businesses, people, and critical national infrastructure. Features the Global Counter Terror & Security Summit and a Live Immersive Arena.',
    targetAudience: 'Security directors, counter-terrorism professionals, critical national infrastructure operators, government security officials, homeland security professionals, law enforcement, and security technology vendors',
    keyTopics: 'Counter-terrorism, homeland security, critical national infrastructure protection, cybersecurity, physical security technologies, crisis response, border security, resilience planning',
    productsToFeature: null,
    preEventGoals: null,
    postEventNotes: null,
    wordpressArticleStatus: 'Not Started',
    articleUrl: null,
  },
  {
    eventName: 'TrustFlight UsersForum',
    businessUnit: 'Redline',
    eventType: 'Forum',
    region: 'EMEA',
    city: 'London',
    country: 'United Kingdom',
    venue: 'TBD (2025 was The Marble Arch Hotel by Thistle)',
    startDate: '2026-09-15',
    endDate: '2026-09-18',
    numberOfDays: 4,
    salesStaffAttending: 0,
    staffNames: null,
    eventBoothCost: 20000,
    estDailyRate: 400,
    totalDailyRate: 0,
    flightCostPerPerson: 0,
    totalFlightCost: 0,
    totalTravelCost: 0,
    totalEventCost: 20000,
    budgetMonth: 'Sep',
    status: 'Planned',
    sponsorshipLevel: null,
    boothNumber: null,
    eventWebsiteUrl: 'https://www.trustflight.com/',
    eventDescription: 'TrustFlight UsersForum is TrustFlight\'s annual customer conference bringing together aviation professionals, technology pioneers, and TrustFlight platform users for product workshops, training sessions, panel discussions, and networking. The inaugural 2025 edition welcomed over 100 customers across 25 sessions over two days.',
    targetAudience: 'TrustFlight customers and prospects, aviation safety managers, continuing airworthiness professionals, airline and MRO IT managers, pilots, quality managers, and TrustFlight product users',
    keyTopics: 'TrustFlight platform updates and roadmap, digital aviation records, electronic tech logs, flight safety, regulatory compliance, digital transformation in aviation, hands-on product workshops',
    productsToFeature: null,
    preEventGoals: null,
    postEventNotes: null,
    wordpressArticleStatus: 'Not Started',
    articleUrl: null,
  },
  {
    eventName: 'TrustFlight UsersForum',
    businessUnit: 'Baines Simmons',
    eventType: 'Forum',
    region: 'EMEA',
    city: 'London',
    country: 'United Kingdom',
    venue: 'TBD (2025 was The Marble Arch Hotel by Thistle)',
    startDate: '2026-09-15',
    endDate: '2026-09-18',
    numberOfDays: 4,
    salesStaffAttending: 0,
    staffNames: null,
    eventBoothCost: 20000,
    estDailyRate: 400,
    totalDailyRate: 0,
    flightCostPerPerson: 0,
    totalFlightCost: 0,
    totalTravelCost: 0,
    totalEventCost: 20000,
    budgetMonth: 'Sep',
    status: 'Planned',
    sponsorshipLevel: null,
    boothNumber: null,
    eventWebsiteUrl: 'https://www.trustflight.com/',
    eventDescription: 'TrustFlight UsersForum is TrustFlight\'s annual customer conference bringing together aviation professionals, technology pioneers, and TrustFlight platform users for product workshops, training sessions, panel discussions, and networking. The inaugural 2025 edition welcomed over 100 customers across 25 sessions over two days.',
    targetAudience: 'TrustFlight customers and prospects, aviation safety managers, continuing airworthiness professionals, airline and MRO IT managers, pilots, quality managers, and TrustFlight product users',
    keyTopics: 'TrustFlight platform updates and roadmap, digital aviation records, electronic tech logs, flight safety, regulatory compliance, digital transformation in aviation, hands-on product workshops',
    productsToFeature: null,
    preEventGoals: null,
    postEventNotes: null,
    wordpressArticleStatus: 'Not Started',
    articleUrl: null,
  },
  {
    eventName: 'TrustFlight UsersForum',
    businessUnit: 'Kenyon',
    eventType: 'Forum',
    region: 'EMEA',
    city: 'London',
    country: 'United Kingdom',
    venue: 'TBD (2025 was The Marble Arch Hotel by Thistle)',
    startDate: '2026-09-15',
    endDate: '2026-09-18',
    numberOfDays: 4,
    salesStaffAttending: 0,
    staffNames: null,
    eventBoothCost: 20000,
    estDailyRate: 400,
    totalDailyRate: 0,
    flightCostPerPerson: 0,
    totalFlightCost: 0,
    totalTravelCost: 0,
    totalEventCost: 20000,
    budgetMonth: 'Sep',
    status: 'Planned',
    sponsorshipLevel: null,
    boothNumber: null,
    eventWebsiteUrl: 'https://www.trustflight.com/',
    eventDescription: 'TrustFlight UsersForum is TrustFlight\'s annual customer conference bringing together aviation professionals, technology pioneers, and TrustFlight platform users for product workshops, training sessions, panel discussions, and networking. The inaugural 2025 edition welcomed over 100 customers across 25 sessions over two days.',
    targetAudience: 'TrustFlight customers and prospects, aviation safety managers, continuing airworthiness professionals, airline and MRO IT managers, pilots, quality managers, and TrustFlight product users',
    keyTopics: 'TrustFlight platform updates and roadmap, digital aviation records, electronic tech logs, flight safety, regulatory compliance, digital transformation in aviation, hands-on product workshops',
    productsToFeature: null,
    preEventGoals: null,
    postEventNotes: null,
    wordpressArticleStatus: 'Not Started',
    articleUrl: null,
  },
  {
    eventName: 'TrustFlight UsersForum',
    businessUnit: 'TrustFlight',
    eventType: 'Forum',
    region: 'EMEA',
    city: 'London',
    country: 'United Kingdom',
    venue: 'TBD (2025 was The Marble Arch Hotel by Thistle)',
    startDate: '2026-09-15',
    endDate: '2026-09-18',
    numberOfDays: 4,
    salesStaffAttending: 0,
    staffNames: null,
    eventBoothCost: 20000,
    estDailyRate: 400,
    totalDailyRate: 0,
    flightCostPerPerson: 0,
    totalFlightCost: 0,
    totalTravelCost: 0,
    totalEventCost: 20000,
    budgetMonth: 'Sep',
    status: 'Planned',
    sponsorshipLevel: null,
    boothNumber: null,
    eventWebsiteUrl: 'https://www.trustflight.com/',
    eventDescription: 'TrustFlight UsersForum is TrustFlight\'s annual customer conference bringing together aviation professionals, technology pioneers, and TrustFlight platform users for product workshops, training sessions, panel discussions, and networking. The inaugural 2025 edition welcomed over 100 customers across 25 sessions over two days.',
    targetAudience: 'TrustFlight customers and prospects, aviation safety managers, continuing airworthiness professionals, airline and MRO IT managers, pilots, quality managers, and TrustFlight product users',
    keyTopics: 'TrustFlight platform updates and roadmap, digital aviation records, electronic tech logs, flight safety, regulatory compliance, digital transformation in aviation, hands-on product workshops',
    productsToFeature: null,
    preEventGoals: null,
    postEventNotes: null,
    wordpressArticleStatus: 'Not Started',
    articleUrl: null,
  },
  {
    eventName: 'NBAA BACE',
    businessUnit: 'Kenyon',
    eventType: 'Trade Show',
    region: 'NA',
    city: 'Las Vegas',
    country: 'United States',
    venue: 'Las Vegas Convention Center, West Hall',
    startDate: "2026-10-20",
    endDate: "2026-10-22",
    numberOfDays: 3,
    salesStaffAttending: 1,
    staffNames: null,
    eventBoothCost: 7500,
    estDailyRate: 400,
    totalDailyRate: 1200,
    flightCostPerPerson: 1500,
    totalFlightCost: 1500,
    totalTravelCost: 2700,
    totalEventCost: 10200,
    budgetMonth: 'Oct',
    status: 'Planned',
    sponsorshipLevel: null,
    boothNumber: null,
    eventWebsiteUrl: 'https://nbaa.org/events/2026-nbaa-business-aviation-convention-exhibition-nbaa-bace/',
    eventDescription: 'NBAA-BACE is the world\'s largest business aviation event and the industry\'s most important annual gathering. Over 20,000 attendees and 1,000+ exhibitors showcase the latest aircraft, avionics, technologies, and services.',
    targetAudience: 'Business aviation professionals including corporate flight departments, aircraft operators, pilots, maintenance technicians, aviation manufacturers, service providers, charter operators, and FBO managers',
    keyTopics: 'Business aircraft showcases, flight operations and safety, sustainable aviation fuel, advanced air mobility, regulatory updates, workforce development, cybersecurity',
    productsToFeature: null,
    preEventGoals: null,
    postEventNotes: null,
    wordpressArticleStatus: 'Not Started',
    articleUrl: null,
  },
  {
    eventName: 'NBAA BACE',
    businessUnit: 'TrustFlight',
    eventType: 'Trade Show',
    region: 'NA',
    city: 'Las Vegas',
    country: 'United States',
    venue: 'Las Vegas Convention Center, West Hall',
    startDate: "2026-10-20",
    endDate: "2026-10-22",
    numberOfDays: 3,
    salesStaffAttending: 3,
    staffNames: null,
    eventBoothCost: 7500,
    estDailyRate: 400,
    totalDailyRate: 3600,
    flightCostPerPerson: 1500,
    totalFlightCost: 4500,
    totalTravelCost: 8100,
    totalEventCost: 15600,
    budgetMonth: 'Oct',
    status: 'Planned',
    sponsorshipLevel: null,
    boothNumber: null,
    eventWebsiteUrl: 'https://nbaa.org/events/2026-nbaa-business-aviation-convention-exhibition-nbaa-bace/',
    eventDescription: 'NBAA-BACE is the world\'s largest business aviation event and the industry\'s most important annual gathering. Over 20,000 attendees and 1,000+ exhibitors showcase the latest aircraft, avionics, technologies, and services.',
    targetAudience: 'Business aviation professionals including corporate flight departments, aircraft operators, pilots, maintenance technicians, aviation manufacturers, service providers, charter operators, and FBO managers',
    keyTopics: 'Business aircraft showcases, flight operations and safety, sustainable aviation fuel, advanced air mobility, regulatory updates, workforce development, cybersecurity',
    productsToFeature: null,
    preEventGoals: null,
    postEventNotes: null,
    wordpressArticleStatus: 'Not Started',
    articleUrl: null,
  },
  {
    eventName: 'WTW/Willis',
    businessUnit: 'TrustFlight',
    eventType: 'Conference',
    region: 'EMEA',
    city: 'Istanbul',
    country: 'Turkey',
    venue: 'TBD',
    startDate: "2026-05-12",
    endDate: "2026-05-14",
    numberOfDays: 2,
    salesStaffAttending: 2,
    staffNames: null,
    eventBoothCost: 10000,
    estDailyRate: 401,
    totalDailyRate: 1604,
    flightCostPerPerson: 0,
    totalFlightCost: 0,
    totalTravelCost: 1604,
    totalEventCost: 11604,
    budgetMonth: 'Oct',
    status: 'Planned',
    sponsorshipLevel: null,
    boothNumber: null,
    eventWebsiteUrl: 'https://www.wtwco.com/en-se/insights/campaigns/global-aviation-and-space-events',
    eventDescription: 'The 23rd annual Willis Aviation Conference brings the airline and insurance industry together to debate the breadth of risks facing aviation. Themed \'Smarter Skies: Managing Risk\', it is the premier meeting point for airline risk managers and aviation insurance professionals.',
    targetAudience: 'Airline risk managers, aviation insurance underwriters, insurance brokers, reinsurers, airline finance executives, and aviation liability professionals',
    keyTopics: 'Aviation insurance market trends, emerging exposures, risk management strategies, geopolitical risks, claims and liability, cyber risk in aviation, sustainability and ESG',
    productsToFeature: null,
    preEventGoals: null,
    postEventNotes: null,
    wordpressArticleStatus: 'Not Started',
    articleUrl: null,
  },
  {
    eventName: 'International Aviation Safety Summit (IASS 2026)',
    businessUnit: 'Baines Simmons',
    eventType: 'Conference',
    region: 'EMEA',
    city: 'Dubai',
    country: 'United Arab Emirates',
    venue: 'TBD',
    startDate: "2026-11-03",
    endDate: "2026-11-05",
    numberOfDays: 3,
    salesStaffAttending: 2,
    staffNames: null,
    eventBoothCost: 5000,
    estDailyRate: 400,
    totalDailyRate: 2400,
    flightCostPerPerson: 1500,
    totalFlightCost: 3000,
    totalTravelCost: 5400,
    totalEventCost: 10400,
    budgetMonth: 'Nov',
    status: 'Planned',
    sponsorshipLevel: null,
    boothNumber: null,
    eventWebsiteUrl: 'https://flightsafety.swoogo.com/IASS2026',
    eventDescription: 'The 79th International Aviation Safety Summit (IASS) is the aviation industry\'s foremost safety event, held annually since 1947. The three-day summit attracts over 350 representatives from more than 50 countries to exchange critical insights and propose strategies to reduce risks in air transportation.',
    targetAudience: 'Aviation safety professionals, airline safety managers, aviation regulators, aircraft manufacturers, air traffic management experts, human factors specialists, maintenance and engineering leaders',
    keyTopics: 'Safety management systems, human factors and mental health, AI and predictive safety, training and practical solutions, maintenance and engineering risks, offshore operations safety, safety data analytics',
    productsToFeature: null,
    preEventGoals: null,
    postEventNotes: null,
    wordpressArticleStatus: 'Not Started',
    articleUrl: null,
  },
  {
    eventName: 'International Aviation Safety Summit (IASS 2026)',
    businessUnit: 'Kenyon',
    eventType: 'Conference',
    region: 'EMEA',
    city: 'Dubai',
    country: 'United Arab Emirates',
    venue: 'TBD',
    startDate: "2026-11-03",
    endDate: "2026-11-05",
    numberOfDays: 3,
    salesStaffAttending: 1,
    staffNames: null,
    eventBoothCost: 5000,
    estDailyRate: 400,
    totalDailyRate: 1200,
    flightCostPerPerson: 1500,
    totalFlightCost: 1500,
    totalTravelCost: 2700,
    totalEventCost: 7700,
    budgetMonth: 'Nov',
    status: 'Planned',
    sponsorshipLevel: null,
    boothNumber: null,
    eventWebsiteUrl: 'https://flightsafety.swoogo.com/IASS2026',
    eventDescription: 'The 79th International Aviation Safety Summit (IASS) is the aviation industry\'s foremost safety event, held annually since 1947. The three-day summit attracts over 350 representatives from more than 50 countries to exchange critical insights and propose strategies to reduce risks in air transportation.',
    targetAudience: 'Aviation safety professionals, airline safety managers, aviation regulators, aircraft manufacturers, air traffic management experts, human factors specialists, maintenance and engineering leaders',
    keyTopics: 'Safety management systems, human factors and mental health, AI and predictive safety, training and practical solutions, maintenance and engineering risks, offshore operations safety, safety data analytics',
    productsToFeature: null,
    preEventGoals: null,
    postEventNotes: null,
    wordpressArticleStatus: 'Not Started',
    articleUrl: null,
  },
  {
    eventName: 'International Aviation Safety Summit (IASS 2026)',
    businessUnit: 'TrustFlight',
    eventType: 'Conference',
    region: 'EMEA',
    city: 'Dubai',
    country: 'United Arab Emirates',
    venue: 'TBD',
    startDate: "2026-11-03",
    endDate: "2026-11-05",
    numberOfDays: 3,
    salesStaffAttending: 2,
    staffNames: null,
    eventBoothCost: 5000,
    estDailyRate: 400,
    totalDailyRate: 2400,
    flightCostPerPerson: 1500,
    totalFlightCost: 3000,
    totalTravelCost: 5400,
    totalEventCost: 10400,
    budgetMonth: 'Nov',
    status: 'Planned',
    sponsorshipLevel: null,
    boothNumber: null,
    eventWebsiteUrl: 'https://flightsafety.swoogo.com/IASS2026',
    eventDescription: 'The 79th International Aviation Safety Summit (IASS) is the aviation industry\'s foremost safety event, held annually since 1947. The three-day summit attracts over 350 representatives from more than 50 countries to exchange critical insights and propose strategies to reduce risks in air transportation.',
    targetAudience: 'Aviation safety professionals, airline safety managers, aviation regulators, aircraft manufacturers, air traffic management experts, human factors specialists, maintenance and engineering leaders',
    keyTopics: 'Safety management systems, human factors and mental health, AI and predictive safety, training and practical solutions, maintenance and engineering risks, offshore operations safety, safety data analytics',
    productsToFeature: null,
    preEventGoals: null,
    postEventNotes: null,
    wordpressArticleStatus: 'Not Started',
    articleUrl: null,
  },
  {
    eventName: 'US & UK Airport Industry Reception',
    businessUnit: 'Redline',
    eventType: 'Dinner/Reception',
    region: 'EMEA',
    city: null,
    country: 'United Kingdom',
    venue: null,
    startDate: null,
    endDate: null,
    numberOfDays: 1,
    salesStaffAttending: 1,
    staffNames: null,
    eventBoothCost: 500,
    estDailyRate: 400,
    totalDailyRate: 400,
    flightCostPerPerson: 0,
    totalFlightCost: 0,
    totalTravelCost: 400,
    totalEventCost: 900,
    budgetMonth: 'Jan',
    status: 'Planned',
    sponsorshipLevel: null,
    boothNumber: null,
    eventWebsiteUrl: null,
    eventDescription: 'A networking reception bringing together senior airport industry stakeholders from the United States and United Kingdom to discuss bilateral aviation matters, trade, and airport development. The event provides an intimate setting for airport operators, regulators, and industry suppliers to build relationships and explore collaboration opportunities.',
    targetAudience: 'Senior airport executives, aviation regulators, government officials, and industry suppliers from the US and UK aviation sectors',
    keyTopics: 'US-UK aviation bilateral relations, airport development, trade opportunities, regulatory cooperation, airport operations',
    productsToFeature: null,
    preEventGoals: null,
    postEventNotes: null,
    wordpressArticleStatus: 'Not Started',
    articleUrl: null,
  },
  {
    eventName: '4th Annual Airport Operations Development, Safety, and Security Conference',
    businessUnit: 'Redline',
    eventType: 'Conference',
    region: 'EMEA',
    city: 'Munich',
    country: 'Germany',
    venue: 'Courtyard by Marriott Munich City Center',
    startDate: '2026-02-19',
    endDate: '2026-02-20',
    numberOfDays: 1,
    salesStaffAttending: 1,
    staffNames: null,
    eventBoothCost: 2000,
    estDailyRate: 400,
    totalDailyRate: 400,
    flightCostPerPerson: 0,
    totalFlightCost: 0,
    totalTravelCost: 400,
    totalEventCost: 2400,
    budgetMonth: 'Feb',
    status: 'Planned',
    sponsorshipLevel: null,
    boothNumber: null,
    eventWebsiteUrl: 'https://www.ryinternational.eu/4th-annual-airport-operations-development-safety-and-security-conference/',
    eventDescription: 'An annual conference organized by R&Y International bringing together high-level aviation industry executives, experts, and professionals to discuss airport operations, safety practices, and security technologies. The event features presentations, active Q&A sessions, and face-to-face networking in an intimate professional setting.',
    targetAudience: 'Airport operations managers, aviation safety professionals, security technology providers, airline operations executives, airport authorities, and regulatory bodies',
    keyTopics: 'Airport operational processes, industry regulations and standards, security technologies and threat detection, safety products and practices, sustainable aviation, data-driven governance',
    productsToFeature: null,
    preEventGoals: null,
    postEventNotes: null,
    wordpressArticleStatus: 'Not Started',
    articleUrl: null,
  },
  {
    eventName: 'Fox Rothschild',
    businessUnit: 'Kenyon',
    eventType: 'Conference',
    region: 'NA',
    city: 'McLean',
    country: 'United States',
    venue: 'The Ritz-Carlton, Tysons Corner',
    startDate: "2027-02-02",
    endDate: "2027-02-04",
    numberOfDays: 3,
    salesStaffAttending: 2,
    staffNames: null,
    eventBoothCost: 500,
    estDailyRate: 400,
    totalDailyRate: 2400,
    flightCostPerPerson: 1500,
    totalFlightCost: 3000,
    totalTravelCost: 5400,
    totalEventCost: 5900,
    budgetMonth: 'Feb',
    status: 'Planned',
    sponsorshipLevel: null,
    boothNumber: null,
    eventWebsiteUrl: 'https://www.foxrothschild.com/events/the-2026-aviation-symposium',
    eventDescription: 'Fox Rothschild\'s annual Aviation Symposium is a leading aviation law conference featuring moderated panels with experienced aviation industry professionals covering cutting-edge legal and regulatory issues. Includes CLE credit opportunities and extensive networking.',
    targetAudience: 'Aviation attorneys, airline in-house counsel, aviation insurance professionals, airline executives, aircraft manufacturers, MRO legal teams, government regulators, and emergency response companies',
    keyTopics: 'Aviation litigation and liability, regulatory compliance (FAA/EASA), accident investigation legal issues, international aviation law, insurance coverage disputes, emerging legal trends',
    productsToFeature: null,
    preEventGoals: null,
    postEventNotes: null,
    wordpressArticleStatus: 'Not Started',
    articleUrl: null,
  },
  {
    eventName: 'IATA World Cargo Symposium',
    businessUnit: 'Redline',
    eventType: 'Conference',
    region: 'LATAM',
    city: 'Lima',
    country: 'Peru',
    venue: null,
    startDate: '2026-03-10',
    endDate: '2026-03-12',
    numberOfDays: 3,
    salesStaffAttending: 2,
    staffNames: null,
    eventBoothCost: 7500,
    estDailyRate: 400,
    totalDailyRate: 2400,
    flightCostPerPerson: 1500,
    totalFlightCost: 3000,
    totalTravelCost: 5400,
    totalEventCost: 12900,
    budgetMonth: 'Mar',
    status: 'Planned',
    sponsorshipLevel: null,
    boothNumber: null,
    eventWebsiteUrl: 'https://www.iata.org/en/events/all/world-cargo-symposium/',
    eventDescription: 'The IATA World Cargo Symposium (WCS) is the largest and most prestigious annual event in the air cargo industry, attracting nearly 2,000 delegates from airlines, freight forwarders, ground handlers, and technology providers. The symposium addresses digitalization, sustainability, safety, security, and operational efficiency across the global air cargo supply chain.',
    targetAudience: 'Air cargo executives, airline cargo divisions, freight forwarders, ground handling companies, shippers, customs authorities, technology providers, and logistics professionals',
    keyTopics: 'Air cargo digitalization, e-commerce logistics, sustainability in air freight, cargo security, customs modernization, lithium battery safety, ONE Record / digital cargo standards',
    productsToFeature: null,
    preEventGoals: null,
    postEventNotes: null,
    wordpressArticleStatus: 'Not Started',
    articleUrl: null,
  },
  {
    eventName: 'IATA Aviation Security Forum',
    businessUnit: 'Redline',
    eventType: 'Forum',
    region: 'EMEA',
    city: null,
    country: null,
    venue: null,
    startDate: null,
    endDate: null,
    numberOfDays: 1,
    salesStaffAttending: 1,
    staffNames: null,
    eventBoothCost: 10000,
    estDailyRate: 400,
    totalDailyRate: 400,
    flightCostPerPerson: 1000,
    totalFlightCost: 1000,
    totalTravelCost: 1400,
    totalEventCost: 11400,
    budgetMonth: 'Mar',
    status: 'Planned',
    sponsorshipLevel: null,
    boothNumber: null,
    eventWebsiteUrl: 'https://www.iata.org/en/programs/security/',
    eventDescription: 'The IATA Aviation Security Forum is an annual gathering of aviation security professionals organized by the International Air Transport Association. It addresses current and emerging threats to aviation security, including geopolitical risks, cybersecurity, and evolving regulatory frameworks.',
    targetAudience: 'Airline security directors, airport security managers, government aviation security regulators, law enforcement agencies, security technology vendors, and civil aviation authorities',
    keyTopics: 'Security management systems (SeMS), cybersecurity in aviation, geopolitical threats, insider threat mitigation, cargo security, emerging threat technologies, regulatory compliance',
    productsToFeature: null,
    preEventGoals: null,
    postEventNotes: null,
    wordpressArticleStatus: 'Not Started',
    articleUrl: null,
  },
  {
    eventName: '3rd EASA FTL/FRM Conference',
    businessUnit: 'Baines Simmons',
    eventType: 'Conference',
    region: 'EMEA',
    city: 'Split',
    country: 'Croatia',
    venue: 'Radisson Blu Resort & Spa, Split',
    startDate: "2026-03-04",
    endDate: "2026-03-05",
    numberOfDays: 2,
    salesStaffAttending: 1,
    staffNames: null,
    eventBoothCost: 2500,
    estDailyRate: 400,
    totalDailyRate: 800,
    flightCostPerPerson: 1500,
    totalFlightCost: 1500,
    totalTravelCost: 2300,
    totalEventCost: 4800,
    budgetMonth: 'Mar',
    status: 'Planned',
    sponsorshipLevel: null,
    boothNumber: null,
    eventWebsiteUrl: 'https://www.easa.europa.eu/en/newsroom-and-events/events/3rd-easa-ftl-fatigue-risk-management-conference',
    eventDescription: 'The 3rd EASA Flight Time Limitations / Fatigue Risk Management Conference brings together regulators, operators, safety leaders, researchers, and crew representatives to discuss the latest developments, challenges, and innovations in FTL and FRM over two days.',
    targetAudience: 'Aviation regulators, airline operators, safety leaders, fatigue risk researchers, crew representatives, human factors specialists, and EASA stakeholders',
    keyTopics: 'FTL rules for air taxi operations, AEMS and single-pilot operations, fatigue risk management in practice, biomathematical models, crew rostering balancing safety and commercial demands',
    productsToFeature: null,
    preEventGoals: null,
    postEventNotes: null,
    wordpressArticleStatus: 'Not Started',
    articleUrl: null,
  },
  {
    eventName: 'EASA Part 21 Workshop & Certification Conference',
    businessUnit: 'Baines Simmons',
    eventType: 'Workshop',
    region: 'EMEA',
    city: 'Cologne',
    country: 'Germany',
    venue: 'EASA Premises (Day 1) / FLORA Koeln (Day 2)',
    startDate: "2026-03-10",
    endDate: "2026-03-11",
    numberOfDays: 2,
    salesStaffAttending: 1,
    staffNames: null,
    eventBoothCost: 500,
    estDailyRate: 400,
    totalDailyRate: 800,
    flightCostPerPerson: 1000,
    totalFlightCost: 1000,
    totalTravelCost: 1800,
    totalEventCost: 2300,
    budgetMonth: 'Mar',
    status: 'Planned',
    sponsorshipLevel: null,
    boothNumber: null,
    eventWebsiteUrl: 'https://www.easa.europa.eu/en/newsroom-and-events/events/easa-part-21-workshop-and-certification-conference-2026',
    eventDescription: 'A two-day hybrid event bringing together industry staff, authorities\' representatives, and EASA experts to discuss updates in EASA product certification activities. Day 1 features Part 21 implementation workshops, Day 2 covers major policy developments at Cologne\'s Botanical Garden.',
    targetAudience: 'Aircraft and component manufacturers, design organisations, production organisations, EASA certification experts, national aviation authorities, Part 21 approval holders',
    keyTopics: 'Part 21 regulatory updates, certification project topics, major policy developments, design organisation approvals, production organisation approvals, continuing airworthiness',
    productsToFeature: null,
    preEventGoals: null,
    postEventNotes: null,
    wordpressArticleStatus: 'Not Started',
    articleUrl: null,
  },
  {
    eventName: 'Royal Navy Flight Safety Conference',
    businessUnit: 'Baines Simmons',
    eventType: 'Conference',
    region: 'EMEA',
    city: 'Yeovilton',
    country: 'United Kingdom',
    venue: 'RNAS Yeovilton',
    startDate: "2026-04-28",
    endDate: "2026-04-28",
    numberOfDays: 1,
    salesStaffAttending: 1,
    staffNames: null,
    eventBoothCost: 1000,
    estDailyRate: 400,
    totalDailyRate: 400,
    flightCostPerPerson: 0,
    totalFlightCost: 0,
    totalTravelCost: 400,
    totalEventCost: 1400,
    budgetMonth: 'Apr',
    status: 'Planned',
    sponsorshipLevel: null,
    boothNumber: null,
    eventWebsiteUrl: null,
    eventDescription: 'The Royal Navy Flight Safety Conference is a military aviation safety event focused on flight safety matters within Royal Navy and Fleet Air Arm operations. This is a non-public military event not widely advertised online.',
    targetAudience: 'Royal Navy aviation personnel, Fleet Air Arm flight safety officers, Military Aviation Authority representatives, defence aviation safety consultants, military aircrew and engineering staff',
    keyTopics: 'Military flight safety, human factors in military aviation, error management, operational risk management, defence aviation safety regulation',
    productsToFeature: null,
    preEventGoals: null,
    postEventNotes: null,
    wordpressArticleStatus: 'Not Started',
    articleUrl: null,
  },
  {
    eventName: 'IATA World Cargo Symposium',
    businessUnit: 'Kenyon',
    eventType: 'Conference',
    region: 'LATAM',
    city: 'Lima',
    country: 'Peru',
    venue: null,
    startDate: '2026-03-10',
    endDate: '2026-03-12',
    numberOfDays: 3,
    salesStaffAttending: 2,
    staffNames: null,
    eventBoothCost: 7500,
    estDailyRate: 400,
    totalDailyRate: 2400,
    flightCostPerPerson: 1500,
    totalFlightCost: 3000,
    totalTravelCost: 5400,
    totalEventCost: 12900,
    budgetMonth: 'Mar',
    status: 'Planned',
    sponsorshipLevel: null,
    boothNumber: null,
    eventWebsiteUrl: 'https://www.iata.org/en/events/all/world-cargo-symposium/',
    eventDescription: 'The IATA World Cargo Symposium (WCS) is the largest and most prestigious annual event in the air cargo industry, attracting nearly 2,000 delegates from airlines, freight forwarders, ground handlers, and technology providers. The symposium addresses digitalization, sustainability, safety, security, and operational efficiency across the global air cargo supply chain.',
    targetAudience: 'Air cargo executives, airline cargo divisions, freight forwarders, ground handling companies, shippers, customs authorities, technology providers, and logistics professionals',
    keyTopics: 'Air cargo digitalization, e-commerce logistics, sustainability in air freight, cargo security, customs modernization, lithium battery safety, ONE Record / digital cargo standards',
    productsToFeature: null,
    preEventGoals: null,
    postEventNotes: null,
    wordpressArticleStatus: 'Not Started',
    articleUrl: null,
  },
  {
    eventName: 'Aircraft IT, Americas',
    businessUnit: 'TrustFlight',
    eventType: 'Conference',
    region: 'NA',
    city: 'Miami',
    country: 'United States',
    venue: 'Hyatt Regency Miami',
    startDate: '2026-03-10',
    endDate: '2026-03-11',
    numberOfDays: 3,
    salesStaffAttending: 2,
    staffNames: null,
    eventBoothCost: 10000,
    estDailyRate: 400,
    totalDailyRate: 2400,
    flightCostPerPerson: 1500,
    totalFlightCost: 3000,
    totalTravelCost: 5400,
    totalEventCost: 15400,
    budgetMonth: 'Mar',
    status: 'Planned',
    sponsorshipLevel: null,
    boothNumber: null,
    eventWebsiteUrl: 'https://aircraftcommerceevents.com/event/2026-airline-aerospace-mro-flight-operations-it-conference-americas/',
    eventDescription: 'The Airline & Aerospace MRO & Flight Operations IT Conference Americas is a two-day event featuring case studies, keynotes, workshops, and vendor showcases covering the latest trends in aviation MRO and flight operations IT.',
    targetAudience: 'Airlines, MROs, OEMs, IT vendors, regulators, consultants, and aviation IT professionals focused on maintenance and flight operations technology',
    keyTopics: 'MRO IT systems, flight operations technology, digital transformation, sustainability/net zero, AI in aviation maintenance, paperless operations, predictive maintenance',
    productsToFeature: null,
    preEventGoals: null,
    postEventNotes: null,
    wordpressArticleStatus: 'Not Started',
    articleUrl: null,
  },
  {
    eventName: 'IATA World Cargo Symposium',
    businessUnit: 'TrustFlight',
    eventType: 'Conference',
    region: 'LATAM',
    city: 'Lima',
    country: 'Peru',
    venue: null,
    startDate: '2026-03-10',
    endDate: '2026-03-12',
    numberOfDays: 3,
    salesStaffAttending: 2,
    staffNames: null,
    eventBoothCost: 7500,
    estDailyRate: 400,
    totalDailyRate: 2400,
    flightCostPerPerson: 1500,
    totalFlightCost: 3000,
    totalTravelCost: 5400,
    totalEventCost: 12900,
    budgetMonth: 'Mar',
    status: 'Planned',
    sponsorshipLevel: null,
    boothNumber: null,
    eventWebsiteUrl: 'https://www.iata.org/en/events/all/world-cargo-symposium/',
    eventDescription: 'The IATA World Cargo Symposium (WCS) is the largest and most prestigious annual event in the air cargo industry, attracting nearly 2,000 delegates from airlines, freight forwarders, ground handlers, and technology providers. The symposium addresses digitalization, sustainability, safety, security, and operational efficiency across the global air cargo supply chain.',
    targetAudience: 'Air cargo executives, airline cargo divisions, freight forwarders, ground handling companies, shippers, customs authorities, technology providers, and logistics professionals',
    keyTopics: 'Air cargo digitalization, e-commerce logistics, sustainability in air freight, cargo security, customs modernization, lithium battery safety, ONE Record / digital cargo standards',
    productsToFeature: null,
    preEventGoals: null,
    postEventNotes: null,
    wordpressArticleStatus: 'Not Started',
    articleUrl: null,
  },
  {
    eventName: 'HeliOffshore Conference',
    businessUnit: 'Baines Simmons',
    eventType: 'Conference',
    region: 'EMEA',
    city: 'Madrid',
    country: 'Spain',
    venue: null,
    startDate: "2026-04-22",
    endDate: "2026-04-24",
    numberOfDays: 3,
    salesStaffAttending: 2,
    staffNames: 'Ian, Karl TBC',
    eventBoothCost: 0,
    estDailyRate: 0,
    totalDailyRate: 0,
    flightCostPerPerson: 0,
    totalFlightCost: 0,
    totalTravelCost: 0,
    totalEventCost: 0,
    budgetMonth: 'Apr',
    status: 'Planned',
    sponsorshipLevel: null,
    boothNumber: null,
    eventWebsiteUrl: null,
    eventDescription: null,
    targetAudience: null,
    keyTopics: null,
    productsToFeature: null,
    preEventGoals: null,
    postEventNotes: null,
    wordpressArticleStatus: 'Not Started',
    articleUrl: null,
  },
  {
    eventName: 'HeliOffshore Conference',
    businessUnit: 'TrustFlight',
    eventType: 'Conference',
    region: 'EMEA',
    city: 'Madrid',
    country: 'Spain',
    venue: null,
    startDate: "2026-04-22",
    endDate: "2026-04-24",
    numberOfDays: 3,
    salesStaffAttending: 2,
    staffNames: 'Ian, Karl TBC',
    eventBoothCost: 0,
    estDailyRate: 0,
    totalDailyRate: 0,
    flightCostPerPerson: 0,
    totalFlightCost: 0,
    totalTravelCost: 0,
    totalEventCost: 0,
    budgetMonth: 'Apr',
    status: 'Planned',
    sponsorshipLevel: null,
    boothNumber: null,
    eventWebsiteUrl: null,
    eventDescription: null,
    targetAudience: null,
    keyTopics: null,
    productsToFeature: null,
    preEventGoals: null,
    postEventNotes: null,
    wordpressArticleStatus: 'Not Started',
    articleUrl: null,
  },
  {
    eventName: 'UK Chamber of Shipping: Safety Culture Conference',
    businessUnit: 'Baines Simmons',
    eventType: 'Conference',
    region: 'EMEA',
    city: 'Glasgow',
    country: 'United Kingdom',
    venue: null,
    startDate: "2026-05-19",
    endDate: "2026-05-20",
    numberOfDays: 2,
    salesStaffAttending: 1,
    staffNames: null,
    eventBoothCost: 0,
    estDailyRate: 0,
    totalDailyRate: 0,
    flightCostPerPerson: 0,
    totalFlightCost: 0,
    totalTravelCost: 400,
    totalEventCost: 400,
    budgetMonth: 'May',
    status: 'Planned',
    sponsorshipLevel: null,
    boothNumber: null,
    eventWebsiteUrl: 'https://www.ukchamberofshipping.com/events/safety-culture-conference-2026',
    eventDescription: 'Safety culture conference hosted by UK Chamber of Shipping covering patterns of incidents and repeat behaviours, human performance, safety leadership, and audits as learning opportunities.',
    targetAudience: 'Maritime safety professionals, shipping operators, seafarers, training managers',
    keyTopics: 'Safety culture, patterns of incidents and repeat behaviours, lithium-ion battery safety, vehicle deck safety, enclosed spaces, fatigue, human performance and safety leadership, audits as learning opportunities',
    productsToFeature: null,
    preEventGoals: null,
    postEventNotes: null,
    wordpressArticleStatus: 'Not Started',
    articleUrl: null,
  },
  {
    eventName: 'UK Flight Safety Committee: Safety Information Exchange 475',
    businessUnit: 'Baines Simmons',
    eventType: 'Conference',
    region: 'EMEA',
    city: 'Filton',
    country: 'United Kingdom',
    venue: 'Airbus, Filton (Hybrid)',
    startDate: "2026-06-16",
    endDate: "2026-06-16",
    numberOfDays: 1,
    salesStaffAttending: 1,
    staffNames: null,
    eventBoothCost: 0,
    estDailyRate: 0,
    totalDailyRate: 0,
    flightCostPerPerson: 0,
    totalFlightCost: 0,
    totalTravelCost: 0,
    totalEventCost: 0,
    budgetMonth: 'Jun',
    status: 'Planned',
    sponsorshipLevel: null,
    boothNumber: null,
    eventWebsiteUrl: 'https://www.ukfsc.co.uk/',
    eventDescription: 'The UK Flight Safety Committee Safety Information Exchange is a regular forum bringing together aviation safety professionals to share information, discuss incidents, and promote safety best practice across the UK aviation industry.',
    targetAudience: 'Aviation safety professionals, flight operations managers, safety managers, regulators, airlines, MROs, and general aviation operators',
    keyTopics: 'Aviation safety information sharing, incident analysis, safety best practice, regulatory updates',
    productsToFeature: null,
    preEventGoals: null,
    postEventNotes: null,
    wordpressArticleStatus: 'Not Started',
    articleUrl: null,
  },
  {
    eventName: 'UK Flight Safety Committee: Safety Information Exchange 476',
    businessUnit: 'Baines Simmons',
    eventType: 'Conference',
    region: 'EMEA',
    city: null,
    country: 'United Kingdom',
    venue: 'Online',
    startDate: "2026-09-08",
    endDate: "2026-09-08",
    numberOfDays: 1,
    salesStaffAttending: 1,
    staffNames: null,
    eventBoothCost: 0,
    estDailyRate: 0,
    totalDailyRate: 0,
    flightCostPerPerson: 0,
    totalFlightCost: 0,
    totalTravelCost: 0,
    totalEventCost: 0,
    budgetMonth: 'Sep',
    status: 'Planned',
    sponsorshipLevel: null,
    boothNumber: null,
    eventWebsiteUrl: 'https://www.ukfsc.co.uk/',
    eventDescription: 'The UK Flight Safety Committee Safety Information Exchange is a regular forum bringing together aviation safety professionals to share information, discuss incidents, and promote safety best practice across the UK aviation industry.',
    targetAudience: 'Aviation safety professionals, flight operations managers, safety managers, regulators, airlines, MROs, and general aviation operators',
    keyTopics: 'Aviation safety information sharing, incident analysis, safety best practice, regulatory updates',
    productsToFeature: null,
    preEventGoals: null,
    postEventNotes: null,
    wordpressArticleStatus: 'Not Started',
    articleUrl: null,
  },
  {
    eventName: 'UK Flight Safety Committee: Safety Information Exchange 477',
    businessUnit: 'Baines Simmons',
    eventType: 'Conference',
    region: 'EMEA',
    city: null,
    country: 'United Kingdom',
    venue: 'Online',
    startDate: "2026-12-08",
    endDate: "2026-12-08",
    numberOfDays: 1,
    salesStaffAttending: 1,
    staffNames: null,
    eventBoothCost: 0,
    estDailyRate: 0,
    totalDailyRate: 0,
    flightCostPerPerson: 0,
    totalFlightCost: 0,
    totalTravelCost: 0,
    totalEventCost: 0,
    budgetMonth: 'Dec',
    status: 'Planned',
    sponsorshipLevel: null,
    boothNumber: null,
    eventWebsiteUrl: 'https://www.ukfsc.co.uk/',
    eventDescription: 'The UK Flight Safety Committee Safety Information Exchange is a regular forum bringing together aviation safety professionals to share information, discuss incidents, and promote safety best practice across the UK aviation industry.',
    targetAudience: 'Aviation safety professionals, flight operations managers, safety managers, regulators, airlines, MROs, and general aviation operators',
    keyTopics: 'Aviation safety information sharing, incident analysis, safety best practice, regulatory updates',
    productsToFeature: null,
    preEventGoals: null,
    postEventNotes: null,
    wordpressArticleStatus: 'Not Started',
    articleUrl: null,
  },
  {
    eventName: 'UK Flight Safety Committee: Safety Information Exchange 478',
    businessUnit: 'Baines Simmons',
    eventType: 'Conference',
    region: 'EMEA',
    city: null,
    country: 'United Kingdom',
    venue: 'Online',
    startDate: "2027-03-16",
    endDate: "2027-03-16",
    numberOfDays: 1,
    salesStaffAttending: 1,
    staffNames: null,
    eventBoothCost: 0,
    estDailyRate: 0,
    totalDailyRate: 0,
    flightCostPerPerson: 0,
    totalFlightCost: 0,
    totalTravelCost: 0,
    totalEventCost: 0,
    budgetMonth: 'Mar',
    status: 'Planned',
    sponsorshipLevel: null,
    boothNumber: null,
    eventWebsiteUrl: 'https://www.ukfsc.co.uk/',
    eventDescription: 'The UK Flight Safety Committee Safety Information Exchange is a regular forum bringing together aviation safety professionals to share information, discuss incidents, and promote safety best practice across the UK aviation industry.',
    targetAudience: 'Aviation safety professionals, flight operations managers, safety managers, regulators, airlines, MROs, and general aviation operators',
    keyTopics: 'Aviation safety information sharing, incident analysis, safety best practice, regulatory updates',
    productsToFeature: null,
    preEventGoals: null,
    postEventNotes: null,
    wordpressArticleStatus: 'Not Started',
    articleUrl: null,
  },
  {
    eventName: 'UK Flight Safety Committee: Safety Information Exchange 479',
    businessUnit: 'Baines Simmons',
    eventType: 'Conference',
    region: 'EMEA',
    city: 'Dublin',
    country: 'Ireland',
    venue: null,
    startDate: "2027-06-15",
    endDate: "2027-06-15",
    numberOfDays: 1,
    salesStaffAttending: 1,
    staffNames: null,
    eventBoothCost: 0,
    estDailyRate: 0,
    totalDailyRate: 0,
    flightCostPerPerson: 0,
    totalFlightCost: 0,
    totalTravelCost: 0,
    totalEventCost: 0,
    budgetMonth: 'Jun',
    status: 'Planned',
    sponsorshipLevel: null,
    boothNumber: null,
    eventWebsiteUrl: 'https://www.ukfsc.co.uk/',
    eventDescription: 'The UK Flight Safety Committee Safety Information Exchange is a regular forum bringing together aviation safety professionals to share information, discuss incidents, and promote safety best practice across the UK aviation industry.',
    targetAudience: 'Aviation safety professionals, flight operations managers, safety managers, regulators, airlines, MROs, and general aviation operators',
    keyTopics: 'Aviation safety information sharing, incident analysis, safety best practice, regulatory updates',
    productsToFeature: null,
    preEventGoals: null,
    postEventNotes: null,
    wordpressArticleStatus: 'Not Started',
    articleUrl: null,
  },
  {
    eventName: 'UK Flight Safety Committee: Safety Information Exchange 480',
    businessUnit: 'Baines Simmons',
    eventType: 'Conference',
    region: 'EMEA',
    city: null,
    country: 'United Kingdom',
    venue: 'Online',
    startDate: "2027-09-07",
    endDate: "2027-09-07",
    numberOfDays: 1,
    salesStaffAttending: 1,
    staffNames: null,
    eventBoothCost: 0,
    estDailyRate: 0,
    totalDailyRate: 0,
    flightCostPerPerson: 0,
    totalFlightCost: 0,
    totalTravelCost: 0,
    totalEventCost: 0,
    budgetMonth: 'Sep',
    status: 'Planned',
    sponsorshipLevel: null,
    boothNumber: null,
    eventWebsiteUrl: 'https://www.ukfsc.co.uk/',
    eventDescription: 'The UK Flight Safety Committee Safety Information Exchange is a regular forum bringing together aviation safety professionals to share information, discuss incidents, and promote safety best practice across the UK aviation industry.',
    targetAudience: 'Aviation safety professionals, flight operations managers, safety managers, regulators, airlines, MROs, and general aviation operators',
    keyTopics: 'Aviation safety information sharing, incident analysis, safety best practice, regulatory updates',
    productsToFeature: null,
    preEventGoals: null,
    postEventNotes: null,
    wordpressArticleStatus: 'Not Started',
    articleUrl: null,
  },
  {
    eventName: 'UK Flight Safety Committee: Safety Information Exchange 481',
    businessUnit: 'Baines Simmons',
    eventType: 'Conference',
    region: 'EMEA',
    city: null,
    country: 'United Kingdom',
    venue: 'Online',
    startDate: "2027-12-07",
    endDate: "2027-12-07",
    numberOfDays: 1,
    salesStaffAttending: 1,
    staffNames: null,
    eventBoothCost: 0,
    estDailyRate: 0,
    totalDailyRate: 0,
    flightCostPerPerson: 0,
    totalFlightCost: 0,
    totalTravelCost: 0,
    totalEventCost: 0,
    budgetMonth: 'Dec',
    status: 'Planned',
    sponsorshipLevel: null,
    boothNumber: null,
    eventWebsiteUrl: 'https://www.ukfsc.co.uk/',
    eventDescription: 'The UK Flight Safety Committee Safety Information Exchange is a regular forum bringing together aviation safety professionals to share information, discuss incidents, and promote safety best practice across the UK aviation industry.',
    targetAudience: 'Aviation safety professionals, flight operations managers, safety managers, regulators, airlines, MROs, and general aviation operators',
    keyTopics: 'Aviation safety information sharing, incident analysis, safety best practice, regulatory updates',
    productsToFeature: null,
    preEventGoals: null,
    postEventNotes: null,
    wordpressArticleStatus: 'Not Started',
    articleUrl: null,
  },
] as const;


